// # Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// #
// # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// #
// # By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function even_fib(n) {
  var fib_start = 1
  var fib_prev = 1
  var total_fib = fib_start + fib_prev
  var evens_total = 0

  while (total_fib < n) {
    evens_total += total_fib
    fib_prev = total_fib + fib_start
    fib_start = fib_prev + total_fib
    total_fib = fib_prev + fib_start
  }

  return evens_total
}
