// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
//
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
//
// Let us list the factors of the first seven triangle numbers:
//
//  1: 1
//  3: 1,3
//  6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
// We can see that 28 is the first triangle number to have over five divisors.
//
// What is the value of the first triangle number to have over five hundred divisors?


function tri_num(n) {
  return (n * (n + 1)) / 2
}


function high_divis(divisors) {
    var num_found = false
    var next_num = 2
    var result;

    while (!num_found) {
        var factors = [1]
        var triange_n = tri_num(next_num++)
        for (var i = 2, j = Math.floor(Math.sqrt(triange_n)); i <= j; i++) {
            if (triange_n % i === 0) {
                var quotent = triange_n / i
                factors.push(j)
                factors.push(quotent)
            }
        }
        factors.push(triange_n)
        if (factors.length > divisors) {
          result = triange_n
          num_found = true
        }
    }

    return result
}
